name: MineCombat
version: "2.0"
api: [1.0.0]
author: onebone, Update by PetteriM1
main: me.onebone.minecombat.MineCombat

permissions:
  minecombat:
    description: Includes all permmissions of MineCombat
